### ISSUE TITLE
Eclipse Themed Asciidoc CSS

### ISSUE THREAD

**Issue by azoitl** [eclipse-platform/ui-best-practices#26]
The HTML we are generating is very plain. I was wandering if there is any CSS available that gives our output an Eclipse look and feel. Especially some header with Eclipse logo and the Eclipse footer with the important links would be great. 

Does anyone have something like that or know how to do it?

**Comment by Bananeweizen** [comment]
Generally this can be done by creating a CSS based theme: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/ However, most of the times that I saw people customizing this, it looked worse than before (because the font styles, distances etc. of the changed parts and the non-changed parts didn't fit together well, and created a Frankenstein's monster look, while the default Asciidoctor theme has been optimized for readability and aesthetics. That's why I'm hesitant to start with a "let's change something to the Eclipse violet/orange" approach. Not sure if something can be copied directly from the website sources instead.

**Comment by azoitl** [comment]
I totally agree here. I'm coming from the Latex world and I'm very strict on my documents for that. So didn't think about adjusting distances or fonts. What would be nice to have some style for the Guidelines for which I used the TIP: tag. There,  for example, in my ascidoc eclipse plugin a light bulb is shown. 

As written above I thought about headers or footers, maybe an outline as side bar. But for the rest I would leave it as is and I was hoping to use something existing.

**Comment by Bananeweizen** [comment]
I've reconfigured the way the TIP, NOTE, ... etc are rendered in my pom creation change. See lines https://github.com/eclipse-platform/ui-best-practices/blob/main/pom.xml#L46 to 49. There are multiple options for that, either plain text (like initially), with images, or with icons from "symbol fonts" (which is what we have now). If you see this differently in the Eclipse preview than in the Maven build output, then we need to add several of those maven attributes also to the asciidoctoreditorconfig (or whatever it's named) file.

**Comment by azoitl** [comment]
With all the improvements happening over the last month. This issue is not valid anymore and it can be closed.
