### ISSUE TITLE
Convert README.md to README.adoc 

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/ui-best-practices#40]
As the documentation in this repo is using Asciidoc, I suggest to convert README.md to adoc as well.

Any concerns? cc @Bananeweizen @azoitl @laeubi?

**Comment by laeubi** [comment]
Is the readme part of the distribution? If not what would be the advantage?

**Comment by vogella** [comment]
> Is the readme part of the distribution? If not what would be the advantage?

Some tech for content and readme. What is the disadvantage in using adoc?

**Comment by laeubi** [comment]
MD seems standard for repo readmes on github, and the rendering of markdown is slightly more compact than adoc, but in the end I think it does not matter much...

**Comment by azoitl** [comment]
I'm also not sure what the advantage would be to turn the readme.md to an adoc. For me the readme is more for people working on the adocs and the adocs the result of this repo to be consumbed by people developing eclipse plugins. So keeping both seperated seems for me a better idea. But as @laeubi I don't have strong preferences for both options.

**Comment by Bananeweizen** [comment]
In our company we also converted repo readme from MD to adoc when switching all documentation content. However, meanwhile I would leave READMEs in MD after experiencing the mixture for a while. All the big hosting software (GitHub, GitLab, Bitbucket, ...) render MD quite well, and many people know the format. Both are not true for Asciidoc, unfortunately.
And having this one README in another format than all other READMEs (of Eclipse repositories) would just make life harder for people trying to update or unify those READMEs at a later point of time.

That's why I would leave it as is (It's also less surprising for people that open the file locally, and might have an editor associated with MD, but not ADOC).

**Comment by BeckerWdf** [comment]
I see two opinions saying "leave it as is" vs. one "change to adoc". What should we do with this? Close it?

**Comment by azoitl** [comment]
I would have a strong preference to leave it as is

**Comment by BeckerWdf** [comment]
So then let's close this for the time being.
