### ISSUE TITLE
Encourage the "One sentence per line rule"

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/ui-best-practices#41]
The readme states that lines should be hard wrapped by 80. Can we increase this to 120?

**Comment by Bananeweizen** [comment]
Fine with me.
However, I would suggest to rewrite that part completely, because the more established documentation rule is:
Once sentence per line.
Just as I demonstrate with this answer.
That will still render as a paragraph with continuous text in Asciidoc's output, but is much easier to refactor.
You can change the order of sentences by moving a line up and down.
Editing the text doesn't move random chunks of 80 characters, but stays in the same line.
And only if a sentence is still way to long, then an artificial hard break is needed,
and it should be at a useful place, like the comma in this sentence.

If others agree, I can add that (and some other best practices for Asciidoc). I would then remove the git hooks stuff completely.

**Comment by vogella** [comment]
+1 for the Once sentence per line  rule
